PROBLEM_BANK = [
    # --- Basics (difficulty 1) ---
    {
        "id": "sum_two",
        "title": "Sum of Two Numbers",
        "description": "Write a function `sum(a, b)` that returns the sum of two numbers.",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function sum(a, b) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [1, 2], "expected": 3},
            {"input": [-1, 5], "expected": 4},
            {"input": [0, 0], "expected": 0},
        ],
        "hints": [
            {"id": "sum_h1", "text": "Use the + operator to add two numbers.", "level": 1},
            {"id": "sum_h2", "text": "return a + b;", "level": 2},
        ],
        "concepts": ["functions", "arithmetic"],
    },
    {
        "id": "max_two",
        "title": "Maximum of Two",
        "description": "Write a function `maxOfTwo(a, b)` that returns the larger of two numbers.",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function maxOfTwo(a, b) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [3, 7], "expected": 7},
            {"input": [10, 2], "expected": 10},
            {"input": [5, 5], "expected": 5},
        ],
        "hints": [
            {"id": "max_h1", "text": "Compare a and b using > or use Math.max().", "level": 1},
            {"id": "max_h2", "text": "return a > b ? a : b;", "level": 2},
        ],
        "concepts": ["conditionals", "comparison"],
    },
    {
        "id": "absolute_val",
        "title": "Absolute Value",
        "description": "Write a function `absolute(n)` that returns the absolute value of a number without using Math.abs().",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function absolute(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [-5], "expected": 5},
            {"input": [3], "expected": 3},
            {"input": [0], "expected": 0},
        ],
        "hints": [
            {"id": "abs_h1", "text": "If the number is negative, negate it.", "level": 1},
            {"id": "abs_h2", "text": "return n < 0 ? -n : n;", "level": 2},
        ],
        "concepts": ["conditionals", "arithmetic"],
    },
    {
        "id": "is_even",
        "title": "Even or Odd",
        "description": "Write a function `isEven(n)` that returns true if n is even, false otherwise.",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function isEven(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [4], "expected": True},
            {"input": [7], "expected": False},
            {"input": [0], "expected": True},
        ],
        "hints": [
            {"id": "even_h1", "text": "Use the modulo operator %.", "level": 1},
            {"id": "even_h2", "text": "return n % 2 === 0;", "level": 2},
        ],
        "concepts": ["modulo", "boolean"],
    },
    # --- Strings (difficulty 2) ---
    {
        "id": "reverse_string",
        "title": "Reverse a String",
        "description": "Write a function `reverseStr(s)` that returns the reversed version of a string.",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function reverseStr(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["hello"], "expected": "olleh"},
            {"input": ["abc"], "expected": "cba"},
            {"input": [""], "expected": ""},
        ],
        "hints": [
            {"id": "rev_h1", "text": "You can split the string into an array, reverse it, then join.", "level": 1},
            {"id": "rev_h2", "text": "return s.split('').reverse().join('');", "level": 2},
        ],
        "concepts": ["strings", "arrays"],
    },
    {
        "id": "is_palindrome",
        "title": "Palindrome Check",
        "description": "Write a function `isPalindrome(s)` that returns true if the string reads the same forwards and backwards (case-insensitive).",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function isPalindrome(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["racecar"], "expected": True},
            {"input": ["hello"], "expected": False},
            {"input": ["Madam"], "expected": True},
        ],
        "hints": [
            {"id": "pal_h1", "text": "Convert to lowercase first, then compare with its reverse.", "level": 1},
            {"id": "pal_h2", "text": "const low = s.toLowerCase(); return low === low.split('').reverse().join('');", "level": 2},
        ],
        "concepts": ["strings", "comparison"],
    },
    {
        "id": "count_vowels",
        "title": "Count Vowels",
        "description": "Write a function `countVowels(s)` that returns the number of vowels (a, e, i, o, u) in a string (case-insensitive).",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function countVowels(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["hello"], "expected": 2},
            {"input": ["AEIOU"], "expected": 5},
            {"input": ["xyz"], "expected": 0},
        ],
        "hints": [
            {"id": "vow_h1", "text": "Loop through each character and check if it's a vowel.", "level": 1},
            {"id": "vow_h2", "text": "return s.toLowerCase().split('').filter(c => 'aeiou'.includes(c)).length;", "level": 2},
        ],
        "concepts": ["strings", "loops", "filtering"],
    },
    # --- Arrays (difficulty 3) ---
    {
        "id": "filter_evens",
        "title": "Filter Even Numbers",
        "description": "Write a function `filterEvens(arr)` that returns a new array containing only the even numbers.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function filterEvens(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 3, 4, 5, 6]], "expected": [2, 4, 6]},
            {"input": [[1, 3, 5]], "expected": []},
            {"input": [[2, 4]], "expected": [2, 4]},
        ],
        "hints": [
            {"id": "filt_h1", "text": "Use the .filter() method with a condition for even numbers.", "level": 1},
            {"id": "filt_h2", "text": "return arr.filter(n => n % 2 === 0);", "level": 2},
        ],
        "concepts": ["arrays", "filter", "modulo"],
    },
    {
        "id": "array_sum",
        "title": "Sum of Array",
        "description": "Write a function `arraySum(arr)` that returns the sum of all numbers in an array.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function arraySum(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 3]], "expected": 6},
            {"input": [[10, -5, 3]], "expected": 8},
            {"input": [[]], "expected": 0},
        ],
        "hints": [
            {"id": "asum_h1", "text": "Use .reduce() to accumulate the sum.", "level": 1},
            {"id": "asum_h2", "text": "return arr.reduce((sum, n) => sum + n, 0);", "level": 2},
        ],
        "concepts": ["arrays", "reduce"],
    },
    {
        "id": "find_max",
        "title": "Find Maximum in Array",
        "description": "Write a function `findMax(arr)` that returns the largest number in an array. Assume the array is non-empty.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function findMax(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 5, 3, 9, 2]], "expected": 9},
            {"input": [[-1, -5, -2]], "expected": -1},
            {"input": [[42]], "expected": 42},
        ],
        "hints": [
            {"id": "fmax_h1", "text": "You can use Math.max with the spread operator.", "level": 1},
            {"id": "fmax_h2", "text": "return Math.max(...arr);", "level": 2},
        ],
        "concepts": ["arrays", "Math"],
    },
    {
        "id": "unique_elements",
        "title": "Remove Duplicates",
        "description": "Write a function `unique(arr)` that returns a new array with duplicates removed, preserving order.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function unique(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 2, 3, 1]], "expected": [1, 2, 3]},
            {"input": [["a", "b", "a"]], "expected": ["a", "b"]},
            {"input": [[]], "expected": []},
        ],
        "hints": [
            {"id": "uniq_h1", "text": "You can use a Set to track seen values.", "level": 1},
            {"id": "uniq_h2", "text": "return [...new Set(arr)];", "level": 2},
        ],
        "concepts": ["arrays", "Set", "deduplication"],
    },
    # --- Recursion (difficulty 4) ---
    {
        "id": "factorial",
        "title": "Factorial",
        "description": "Write a function `factorial(n)` that returns n! using recursion. Assume n >= 0.",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function factorial(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [5], "expected": 120},
            {"input": [0], "expected": 1},
            {"input": [1], "expected": 1},
        ],
        "hints": [
            {"id": "fact_h1", "text": "Base case: 0! = 1. Recursive case: n! = n * (n-1)!.", "level": 1},
            {"id": "fact_h2", "text": "if (n <= 1) return 1; return n * factorial(n - 1);", "level": 2},
        ],
        "concepts": ["recursion", "base case"],
    },
    {
        "id": "fibonacci",
        "title": "Fibonacci Number",
        "description": "Write a function `fib(n)` that returns the nth Fibonacci number (0-indexed: fib(0)=0, fib(1)=1, fib(2)=1, ...).",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function fib(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [0], "expected": 0},
            {"input": [1], "expected": 1},
            {"input": [6], "expected": 8},
            {"input": [10], "expected": 55},
        ],
        "hints": [
            {"id": "fib_h1", "text": "Base cases: fib(0)=0, fib(1)=1. Otherwise fib(n)=fib(n-1)+fib(n-2).", "level": 1},
            {"id": "fib_h2", "text": "Use iteration or memoization for efficiency.", "level": 2},
        ],
        "concepts": ["recursion", "dynamic programming"],
    },
    {
        "id": "power",
        "title": "Power Function",
        "description": "Write a function `power(base, exp)` that computes base^exp using recursion. Assume exp >= 0.",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function power(base, exp) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [2, 3], "expected": 8},
            {"input": [5, 0], "expected": 1},
            {"input": [3, 4], "expected": 81},
        ],
        "hints": [
            {"id": "pow_h1", "text": "Base case: anything to the power of 0 is 1.", "level": 1},
            {"id": "pow_h2", "text": "if (exp === 0) return 1; return base * power(base, exp - 1);", "level": 2},
        ],
        "concepts": ["recursion", "exponentiation"],
    },
    # --- Data Structures (difficulty 5) ---
    {
        "id": "stack_impl",
        "title": "Implement a Stack",
        "description": "Implement a Stack class with push(val), pop(), and peek() methods. pop() and peek() should return undefined on empty stack.",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "class Stack {\n  constructor() {\n    // your code here\n  }\n  push(val) {\n    // your code here\n  }\n  pop() {\n    // your code here\n  }\n  peek() {\n    // your code here\n  }\n}\n",
        "test_cases": [
            {"input": ["push:1", "push:2", "peek", "pop", "peek"], "expected": [None, None, 2, 2, 1]},
            {"input": ["pop", "push:5", "pop"], "expected": [None, None, 5]},
        ],
        "hints": [
            {"id": "stack_h1", "text": "Use an array as the internal storage. Push adds to end, pop removes from end.", "level": 1},
            {"id": "stack_h2", "text": "this.items = []; push: this.items.push(val); pop: return this.items.pop();", "level": 2},
        ],
        "concepts": ["stack", "LIFO", "class"],
    },
    {
        "id": "two_sum",
        "title": "Two Sum",
        "description": "Write a function `twoSum(nums, target)` that returns the indices of two numbers that add up to the target. Assume exactly one solution exists.",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "function twoSum(nums, target) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[2, 7, 11, 15], 9], "expected": [0, 1]},
            {"input": [[3, 2, 4], 6], "expected": [1, 2]},
        ],
        "hints": [
            {"id": "ts_h1", "text": "Use a hash map to store each number's index as you iterate.", "level": 1},
            {"id": "ts_h2", "text": "For each num, check if (target - num) is already in the map.", "level": 2},
        ],
        "concepts": ["hash map", "arrays", "optimization"],
    },
    {
        "id": "flatten_array",
        "title": "Flatten Nested Array",
        "description": "Write a function `flatten(arr)` that takes a nested array and returns a single flat array. E.g. [1,[2,[3]]] -> [1,2,3].",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "function flatten(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[[1, [2, [3]]]]], "expected": [1, 2, 3]},
            {"input": [[[1, 2, 3]]], "expected": [1, 2, 3]},
            {"input": [[[]]], "expected": []},
        ],
        "hints": [
            {"id": "flat_h1", "text": "Use recursion: if an element is an array, recursively flatten it.", "level": 1},
            {"id": "flat_h2", "text": "return arr.reduce((acc, item) => acc.concat(Array.isArray(item) ? flatten(item) : item), []);", "level": 2},
        ],
        "concepts": ["recursion", "arrays", "flatten"],
    },
    # --- Basics continued (difficulty 1) ---
    {
        "id": "celsius_to_fahrenheit",
        "title": "Celsius to Fahrenheit",
        "description": "Write a function `celsiusToFahrenheit(c)` that converts Celsius to Fahrenheit. Formula: F = C * 9/5 + 32.",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function celsiusToFahrenheit(c) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [0], "expected": 32},
            {"input": [100], "expected": 212},
            {"input": [-40], "expected": -40},
        ],
        "hints": [
            {"id": "ctf_h1", "text": "Apply the formula: F = C * 9/5 + 32.", "level": 1},
            {"id": "ctf_h2", "text": "return c * 9 / 5 + 32;", "level": 2},
        ],
        "concepts": ["arithmetic", "functions"],
    },
    {
        "id": "is_prime",
        "title": "Is Prime",
        "description": "Write a function `isPrime(n)` that returns true if n is a prime number, false otherwise. Assume n >= 2.",
        "difficulty": 1,
        "category": "basics",
        "starter_code": "function isPrime(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [2], "expected": True},
            {"input": [7], "expected": True},
            {"input": [9], "expected": False},
            {"input": [13], "expected": True},
        ],
        "hints": [
            {"id": "prime_h1", "text": "Check divisibility from 2 up to Math.sqrt(n).", "level": 1},
            {"id": "prime_h2", "text": "for (let i=2; i<=Math.sqrt(n); i++) { if (n%i===0) return false; } return true;", "level": 2},
        ],
        "concepts": ["loops", "arithmetic", "boolean"],
    },
    # --- Strings continued (difficulty 2) ---
    {
        "id": "title_case",
        "title": "Title Case",
        "description": "Write a function `titleCase(s)` that capitalizes the first letter of each word in a string.",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function titleCase(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["hello world"], "expected": "Hello World"},
            {"input": ["the quick brown fox"], "expected": "The Quick Brown Fox"},
            {"input": ["already Done"], "expected": "Already Done"},
        ],
        "hints": [
            {"id": "tc_h1", "text": "Split into words, capitalize each, then join.", "level": 1},
            {"id": "tc_h2", "text": "return s.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');", "level": 2},
        ],
        "concepts": ["strings", "array methods"],
    },
    {
        "id": "count_char",
        "title": "Count Character Occurrences",
        "description": "Write a function `countChar(s, char)` that returns how many times `char` appears in string `s` (case-sensitive).",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function countChar(s, char) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["hello", "l"], "expected": 2},
            {"input": ["banana", "a"], "expected": 3},
            {"input": ["abc", "z"], "expected": 0},
        ],
        "hints": [
            {"id": "cc_h1", "text": "Split the string by the character and count splits minus 1.", "level": 1},
            {"id": "cc_h2", "text": "return s.split(char).length - 1;", "level": 2},
        ],
        "concepts": ["strings", "counting"],
    },
    {
        "id": "longest_word",
        "title": "Longest Word",
        "description": "Write a function `longestWord(sentence)` that returns the longest word in a sentence. If there's a tie, return the first one.",
        "difficulty": 2,
        "category": "strings",
        "starter_code": "function longestWord(sentence) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["the quick brown fox"], "expected": "quick"},
            {"input": ["I love JavaScript"], "expected": "JavaScript"},
            {"input": ["one"], "expected": "one"},
        ],
        "hints": [
            {"id": "lw_h1", "text": "Split into words, then reduce to find the longest.", "level": 1},
            {"id": "lw_h2", "text": "return s.split(' ').reduce((a, b) => b.length > a.length ? b : a);", "level": 2},
        ],
        "concepts": ["strings", "reduce"],
    },
    # --- Arrays continued (difficulty 3) ---
    {
        "id": "rotate_array",
        "title": "Rotate Array Left",
        "description": "Write a function `rotateLeft(arr, k)` that returns a new array rotated left by k positions. E.g. rotateLeft([1,2,3,4,5], 2) => [3,4,5,1,2].",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function rotateLeft(arr, k) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 3, 4, 5], 2], "expected": [3, 4, 5, 1, 2]},
            {"input": [[1, 2, 3], 0], "expected": [1, 2, 3]},
            {"input": [[1, 2, 3], 3], "expected": [1, 2, 3]},
        ],
        "hints": [
            {"id": "rot_h1", "text": "Use slice and concatenation. Rotate by k % arr.length to handle large k.", "level": 1},
            {"id": "rot_h2", "text": "const n = k % arr.length; return [...arr.slice(n), ...arr.slice(0, n)];", "level": 2},
        ],
        "concepts": ["arrays", "slice"],
    },
    {
        "id": "chunk_array",
        "title": "Chunk Array",
        "description": "Write a function `chunkArray(arr, size)` that splits an array into chunks of the given size. The last chunk may be smaller.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function chunkArray(arr, size) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 3, 4, 5], 2], "expected": [[1, 2], [3, 4], [5]]},
            {"input": [[1, 2, 3], 3], "expected": [[1, 2, 3]]},
            {"input": [[], 2], "expected": []},
        ],
        "hints": [
            {"id": "chunk_h1", "text": "Use a loop with slice to extract chunks of `size` at a time.", "level": 1},
            {"id": "chunk_h2", "text": "const res=[]; for(let i=0;i<arr.length;i+=size) res.push(arr.slice(i,i+size)); return res;", "level": 2},
        ],
        "concepts": ["arrays", "loops", "slice"],
    },
    {
        "id": "array_intersection",
        "title": "Array Intersection",
        "description": "Write a function `intersection(a, b)` that returns a sorted array of elements that appear in both arrays (no duplicates).",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function intersection(a, b) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 2, 3, 4], [3, 4, 5, 6]], "expected": [3, 4]},
            {"input": [[1, 2], [3, 4]], "expected": []},
            {"input": [[1, 1, 2], [1, 2, 2]], "expected": [1, 2]},
        ],
        "hints": [
            {"id": "inter_h1", "text": "Use a Set for one array, then filter the other to keep only matches.", "level": 1},
            {"id": "inter_h2", "text": "return [...new Set(a.filter(x => b.includes(x)))].sort((x,y)=>x-y);", "level": 2},
        ],
        "concepts": ["arrays", "Set", "filter"],
    },
    {
        "id": "second_largest",
        "title": "Second Largest Number",
        "description": "Write a function `secondLargest(arr)` that returns the second largest unique number in an array. Return null if it doesn't exist.",
        "difficulty": 3,
        "category": "arrays",
        "starter_code": "function secondLargest(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[3, 1, 4, 1, 5, 9]], "expected": 5},
            {"input": [[1, 1, 1]], "expected": None},
            {"input": [[10, 20]], "expected": 10},
        ],
        "hints": [
            {"id": "sl_h1", "text": "Sort unique values in descending order, then pick index 1.", "level": 1},
            {"id": "sl_h2", "text": "const sorted = [...new Set(arr)].sort((a,b)=>b-a); return sorted[1] ?? null;", "level": 2},
        ],
        "concepts": ["arrays", "Set", "sorting"],
    },
    # --- Sorting (difficulty 3) ---
    {
        "id": "bubble_sort",
        "title": "Bubble Sort",
        "description": "Write a function `bubbleSort(arr)` that returns the array sorted in ascending order using the bubble sort algorithm.",
        "difficulty": 3,
        "category": "sorting",
        "starter_code": "function bubbleSort(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[5, 3, 8, 1, 2]], "expected": [1, 2, 3, 5, 8]},
            {"input": [[1]], "expected": [1]},
            {"input": [[-3, 0, 5, -1]], "expected": [-3, -1, 0, 5]},
        ],
        "hints": [
            {"id": "bs_h1", "text": "Repeatedly swap adjacent elements that are out of order.", "level": 1},
            {"id": "bs_h2", "text": "const a=[...arr]; for(let i=0;i<a.length;i++) for(let j=0;j<a.length-i-1;j++) if(a[j]>a[j+1]) [a[j],a[j+1]]=[a[j+1],a[j]]; return a;", "level": 2},
        ],
        "concepts": ["sorting", "loops", "swapping"],
    },
    {
        "id": "merge_sorted",
        "title": "Merge Sorted Arrays",
        "description": "Write a function `mergeSorted(a, b)` that merges two sorted arrays into one sorted array.",
        "difficulty": 3,
        "category": "sorting",
        "starter_code": "function mergeSorted(a, b) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 3, 5], [2, 4, 6]], "expected": [1, 2, 3, 4, 5, 6]},
            {"input": [[], [1, 2]], "expected": [1, 2]},
            {"input": [[1, 2, 3], []], "expected": [1, 2, 3]},
        ],
        "hints": [
            {"id": "ms_h1", "text": "Use two pointers, one for each array, and pick the smaller element each step.", "level": 1},
            {"id": "ms_h2", "text": "You can also concatenate and sort: return [...a, ...b].sort((x,y)=>x-y);", "level": 2},
        ],
        "concepts": ["sorting", "merge", "two pointers"],
    },
    # --- Recursion continued (difficulty 4) ---
    {
        "id": "sum_digits",
        "title": "Sum of Digits",
        "description": "Write a function `sumDigits(n)` that returns the sum of the digits of a non-negative integer using recursion. E.g. sumDigits(123) = 6.",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function sumDigits(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [123], "expected": 6},
            {"input": [0], "expected": 0},
            {"input": [9999], "expected": 36},
        ],
        "hints": [
            {"id": "sd_h1", "text": "Base case: if n < 10, return n. Otherwise return n%10 + sumDigits(Math.floor(n/10)).", "level": 1},
            {"id": "sd_h2", "text": "if (n < 10) return n; return n % 10 + sumDigits(Math.floor(n / 10));", "level": 2},
        ],
        "concepts": ["recursion", "arithmetic"],
    },
    {
        "id": "binary_search",
        "title": "Binary Search",
        "description": "Write a function `binarySearch(arr, target)` that searches a sorted array and returns the index of target, or -1 if not found.",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function binarySearch(arr, target) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[1, 3, 5, 7, 9], 5], "expected": 2},
            {"input": [[1, 3, 5, 7, 9], 6], "expected": -1},
            {"input": [[2], 2], "expected": 0},
        ],
        "hints": [
            {"id": "bsearch_h1", "text": "Track low and high pointers, check the mid element each iteration.", "level": 1},
            {"id": "bsearch_h2", "text": "let lo=0, hi=arr.length-1; while(lo<=hi){const mid=Math.floor((lo+hi)/2); if(arr[mid]===target) return mid; arr[mid]<target?lo=mid+1:hi=mid-1;} return -1;", "level": 2},
        ],
        "concepts": ["search", "divide and conquer"],
    },
    {
        "id": "flatten_depth",
        "title": "Flatten to Depth",
        "description": "Write a function `flattenDepth(arr, depth)` that flattens a nested array up to the given depth. E.g. flattenDepth([1,[2,[3,[4]]]], 2) => [1,2,3,[4]].",
        "difficulty": 4,
        "category": "recursion",
        "starter_code": "function flattenDepth(arr, depth) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[[1, [2, [3, [4]]]]], 2], "expected": [1, 2, 3, [4]]},
            {"input": [[[1, [2]]], 1], "expected": [1, [2]]},
            {"input": [[[1, 2, 3]], 0], "expected": [[1, 2, 3]]},
        ],
        "hints": [
            {"id": "fd_h1", "text": "Base: depth 0 returns arr as-is. Otherwise reduce: if element is array, recursively flatten with depth-1.", "level": 1},
            {"id": "fd_h2", "text": "if (depth===0) return arr; return arr.reduce((acc,v)=>acc.concat(Array.isArray(v)?flattenDepth(v,depth-1):v),[]);", "level": 2},
        ],
        "concepts": ["recursion", "arrays"],
    },
    # --- Dynamic Programming (difficulty 4) ---
    {
        "id": "climb_stairs",
        "title": "Climb Stairs",
        "description": "Write a function `climbStairs(n)` that returns the number of distinct ways to climb n stairs, taking 1 or 2 steps at a time.",
        "difficulty": 4,
        "category": "dynamic_programming",
        "starter_code": "function climbStairs(n) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [1], "expected": 1},
            {"input": [3], "expected": 3},
            {"input": [5], "expected": 8},
        ],
        "hints": [
            {"id": "cs_h1", "text": "This is the Fibonacci pattern: ways(n) = ways(n-1) + ways(n-2).", "level": 1},
            {"id": "cs_h2", "text": "let a=1,b=1; for(let i=2;i<=n;i++){[a,b]=[b,a+b];} return b;", "level": 2},
        ],
        "concepts": ["dynamic programming", "fibonacci"],
    },
    {
        "id": "max_subarray",
        "title": "Maximum Subarray Sum",
        "description": "Write a function `maxSubarray(arr)` that returns the maximum sum of any contiguous subarray (Kadane's algorithm).",
        "difficulty": 4,
        "category": "dynamic_programming",
        "starter_code": "function maxSubarray(arr) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], "expected": 6},
            {"input": [[1]], "expected": 1},
            {"input": [[-1, -2, -3]], "expected": -1},
        ],
        "hints": [
            {"id": "msa_h1", "text": "Track the running max sum ending at each index. Reset if it drops below the current element.", "level": 1},
            {"id": "msa_h2", "text": "let max=arr[0], cur=arr[0]; for(let i=1;i<arr.length;i++){cur=Math.max(arr[i],cur+arr[i]); max=Math.max(max,cur);} return max;", "level": 2},
        ],
        "concepts": ["dynamic programming", "Kadane's algorithm"],
    },
    # --- Data Structures continued (difficulty 5) ---
    {
        "id": "is_balanced",
        "title": "Balanced Parentheses",
        "description": "Write a function `isBalanced(s)` that returns true if the string's brackets are balanced. Supports (, ), [, ], {, }.",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "function isBalanced(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["({[]})"], "expected": True},
            {"input": ["([)]"], "expected": False},
            {"input": [""], "expected": True},
            {"input": ["{[}"], "expected": False},
        ],
        "hints": [
            {"id": "ib_h1", "text": "Use a stack. Push opening brackets; for closing brackets, check if the top matches.", "level": 1},
            {"id": "ib_h2", "text": "const map={')':'(', ']':'[', '}':'{'}; const stack=[]; for(const c of s){if('([{'.includes(c)) stack.push(c); else if(stack.pop()!==map[c]) return false;} return stack.length===0;", "level": 2},
        ],
        "concepts": ["stack", "strings", "parsing"],
    },
    {
        "id": "longest_common_prefix",
        "title": "Longest Common Prefix",
        "description": "Write a function `longestCommonPrefix(strs)` that returns the longest common prefix string among an array of strings. Return '' if none.",
        "difficulty": 5,
        "category": "strings",
        "starter_code": "function longestCommonPrefix(strs) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [["flower", "flow", "flight"]], "expected": "fl"},
            {"input": [["dog", "racecar", "car"]], "expected": ""},
            {"input": [["interstellar", "internet", "internal"]], "expected": "inter"},
        ],
        "hints": [
            {"id": "lcp_h1", "text": "Sort the array and compare only the first and last strings — their common prefix is the answer.", "level": 1},
            {"id": "lcp_h2", "text": "const sorted=strs.slice().sort(); const a=sorted[0],b=sorted[sorted.length-1]; let i=0; while(i<a.length&&a[i]===b[i]) i++; return a.slice(0,i);", "level": 2},
        ],
        "concepts": ["strings", "sorting"],
    },
    {
        "id": "group_anagrams",
        "title": "Group Anagrams",
        "description": "Write a function `groupAnagrams(strs)` that groups strings that are anagrams of each other. Return an array of groups, each group sorted alphabetically. The groups themselves should be sorted by their first element.",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "function groupAnagrams(strs) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [["eat", "tea", "tan", "ate", "nat", "bat"]], "expected": [["ate", "eat", "tea"], ["bat"], ["nat", "tan"]]},
            {"input": [[""]], "expected": [[""]]},
            {"input": [["a"]], "expected": [["a"]]},
        ],
        "hints": [
            {"id": "ga_h1", "text": "Use a map keyed by the sorted version of each string to group anagrams.", "level": 1},
            {"id": "ga_h2", "text": "const map={}; for(const s of strs){const k=s.split('').sort().join(''); (map[k]=map[k]||[]).push(s);} return Object.values(map).map(g=>g.sort()).sort((a,b)=>a[0].localeCompare(b[0]));", "level": 2},
        ],
        "concepts": ["hash map", "strings", "sorting"],
    },
    {
        "id": "matrix_diagonal_sum",
        "title": "Matrix Diagonal Sum",
        "description": "Write a function `diagonalSum(matrix)` that returns the sum of both diagonals of a square matrix, without double-counting the center element.",
        "difficulty": 5,
        "category": "arrays",
        "starter_code": "function diagonalSum(matrix) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], "expected": 25},
            {"input": [[[1, 1], [1, 1]]], "expected": 4},
            {"input": [[[5]]], "expected": 5},
        ],
        "hints": [
            {"id": "diag_h1", "text": "Main diagonal: matrix[i][i]. Anti-diagonal: matrix[i][n-1-i]. Subtract center if n is odd.", "level": 1},
            {"id": "diag_h2", "text": "const n=matrix.length; let sum=0; for(let i=0;i<n;i++){sum+=matrix[i][i]+matrix[i][n-1-i];} if(n%2===1) sum-=matrix[Math.floor(n/2)][Math.floor(n/2)]; return sum;", "level": 2},
        ],
        "concepts": ["arrays", "matrix", "loops"],
    },
    {
        "id": "word_frequency",
        "title": "Word Frequency",
        "description": "Write a function `wordFrequency(s)` that returns an object mapping each word to its frequency in the string (case-insensitive, words split by spaces).",
        "difficulty": 5,
        "category": "data_structures",
        "starter_code": "function wordFrequency(s) {\n  // your code here\n}\n",
        "test_cases": [
            {"input": ["the cat sat on the mat"], "expected": {"the": 2, "cat": 1, "sat": 1, "on": 1, "mat": 1}},
            {"input": ["hello Hello HELLO"], "expected": {"hello": 3}},
            {"input": ["one"], "expected": {"one": 1}},
        ],
        "hints": [
            {"id": "wf_h1", "text": "Split the string into words (lowercase), then count with an object or Map.", "level": 1},
            {"id": "wf_h2", "text": "const freq={}; for(const w of s.toLowerCase().split(' ')){freq[w]=(freq[w]||0)+1;} return freq;", "level": 2},
        ],
        "concepts": ["hash map", "strings", "counting"],
    },
]


def get_problem(problem_id: str) -> dict | None:
    for p in PROBLEM_BANK:
        if p["id"] == problem_id:
            return p
    return None


def get_all_problems() -> list[dict]:
    return PROBLEM_BANK
